apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app-tst
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/raftAtGit/argocd-demo
    path: apps/tst
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true